# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsMyETDqv12Go5u36wx4q1kz9imTzQhl
"""

# app.py
import streamlit as st
import pandas as pd

# Título
st.title("Registro de mantenimiento")

# Cargar archivo existente
if 'df' not in st.session_state:
    st.session_state.df = pd.DataFrame(columns=['Equipo', 'Mes', 'Horas'])

# Formulario para agregar nuevo registro
with st.form("nuevo_registro"):
    equipo = st.selectbox("Equipo", ['Equipo 1', 'Equipo 2', 'Equipo 3', 'Equipo 4', 'Medrano', 'Viamonte', 'Centro'])
    mes = st.selectbox("Mes", ['Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
    horas = st.number_input("Horas de mantenimiento", min_value=0.0, step=0.25)

    submitted = st.form_submit_button("Agregar")

    if submitted:
        nuevo = pd.DataFrame({'Equipo': [equipo], 'Mes': [mes], 'Horas': [horas]})
        st.session_state.df = pd.concat([st.session_state.df, nuevo], ignore_index=True)
        st.success("Registro agregado")

# Mostrar tabla actualizada
st.subheader("Registros actuales")
st.dataframe(st.session_state.df)

# Descargar como CSV
csv = st.session_state.df.to_csv(index=False).encode('utf-8')
st.download_button("Descargar CSV", csv, "mantenimiento.csv", "text/csv")